name: the_project_hariyal
description: A project by shanmukeshwar and gautham.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.7
  material_design_icons_flutter: ^4.0.5345
  geolocator: ^5.3.2+2
  permission_handler: ^5.0.1+1
  location: ^3.0.2
  fluttertoast: ^4.0.1
  multi_image_picker: ^4.6.7
  shared_preferences: ^0.5.7+3
  flutter_phoenix: ^0.1.0
  firebase_storage: ^3.1.6
  path_provider: ^1.6.11
  flutter_absolute_path: ^1.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true